# Generated by Django 5.0.2 on 2024-03-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petty_Cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminexpense',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
